### PR TITLE
Grupp b2019 w22#7382

### LINKED ISSUE #7382: Sorting on Firstname in Resulted do not work, sorts on lastname instead. Sorting on lastname works though.
When sorting (either by pressing the header or by the dropdown menu) on firstname it sorts on lastname.

### PR DESCRIPTION
**Pull request by a17oscno**
Fixes #7382 

It now works to sort on firstname again with the dropdown menu.

link: https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732

### CODE REVIEW

File: DuggaSys/resulted.js [hunk 1]
```diff
@@ -304,6 +304,10 @@ function sorttype(t) {
 
 	var col;
 	var dir;
+
+  localStorage.setItem("lena_" + querystring['cid'] + "-" + querystring['coursevers'] + "-sortcol", col);
```
Comment (c17johha) [inline DuggaSys/resulted.js]: I'm unable to use tab to get the correct indentation, fix that.

File: DuggaSys/resulted.js [hunk 2]
```diff
@@ -315,6 +319,7 @@ function sorttype(t) {
 		typechanged = false;
 		var allColumnIds = myTable.getColumnOrder();
 		myTable.toggleSortStatus(allColumnIds[col],dir);
+    console.log("col: "+col+" dir: "+dir+" t: "+t);
```
Comment (c17johha) [inline DuggaSys/resulted.js]:
```suggestion
```

File: DuggaSys/resulted.js [hunk 3]
```diff
@@ -284,7 +284,7 @@ function leaves() {
 function sorttype(t) {
   if(t == 0){
```
Comment (c17johha) [inline DuggaSys/resulted.js]: Fix indentation 285-289

File: DuggaSys/resulted.js (hunk 1 above)
Comment (a17oscno) [reply DuggaSys/resulted.js]: The code has correct indentation when I opened it in Atom, Visual Code and Notepad. So I can't really change it because it isn't wrong for me.

File: DuggaSys/resulted.js (hunk 3 above)
Comment (a17oscno) [reply DuggaSys/resulted.js]: The indenting is fixed

**Comment by c17johha** [comment]
image
The indentation is still not fixed.

**Comment by a17oscno** [comment]
yes, yes it does. @c17johha 

image
